### ISSUE TITLE
Use preload instead of prefetch for these resources.

### ISSUE THREAD

**Issue by pxwee5** [disqus/disqus-install-examples#32]
See Chrome warnings
![image](https://user-images.githubusercontent.com/14123790/50742117-c22c6200-126b-11e9-8a77-f6ff4f260337.png)

And Addy's comment about using preload and prefetch.
https://github.com/GoogleChromeLabs/preload-webpack-plugin/issues/8#issuecomment-277105884

**Comment by dmatt** [comment]
Thanks for submitting this issue @pxwee5. @Hovspian confirmed that this is fixed now (D29769, for internal tracking) so I'm closing this.
