### ISSUE TITLE
AMP comment count

### ISSUE THREAD

**Issue by maciejmackowiak** [disqus/disqus-install-examples#38]
Hi,
Great work on Disqus AMP, it works without any problems but in our implemented we would also like to have comment count but the AMP pages are cached on CDN's so it is impossible to make it work.
Are you planning to implement solution for it for example using <amp-script>?
https://amp.dev/documentation/components/amp-script/?format=websites
Here are some examples:
https://amp.dev/documentation/examples/components/amp-script/?format=websites

Thanks in advance
Maciej

**Comment by archon810** [comment]
After bringing this up to Disqus engineering, there's no current recommendation for this feature, but they're looking into it.

**Comment by maciejmackowiak** [comment]
Any updates?

We could probably use this endpoint:
https://disqus.com/api/3.0/threads/details.json?api_key=......&forum=......&thread:ident=......
But in order to do that it must allow cors requests, also this endpoint has a lot of data we don't need for comment count so I think the best solution is that you will create another endpoint that returns only post/thread ID and comments number and also it allows cors requests

Then it could be used like this: 
JSON from your enpoint:
`{"thread/post_id":"comments_number"}`
AMP html:
`<amp-list noloading="" single-item="" items="." layout="fixed-height" height="12" src="https://disqus.com/api/3.0/[post-count-endpoint]">
<template type="amp-mustache">{{thread/post_id}}</template>
<span placeholder="">...</span>
</amp-list>`

**Comment by Hovspian** [comment]
Hi,

We updated our AMP install instructions to include information about comment counts using our count.js in #39. It still takes a while for comments counts to update because they're cached

I don’t see any issues using an `<amp-list>` and our API so feel free to continue using it if you’re happy with it. However, because not every publisher has API access, I opted for another solution using count.js like you typically see on sites showing their comment counts.

Best,
Hovsep

**Comment by archon810** [comment]
Thank you, @Hovspian. To clarify, does this solution work on all comment counts on the page and batches multiple comment count requests into one call?

**Comment by Hovspian** [comment]
Yes it will. It works the same way as the [comment counts for non-AMP pages](https://help.disqus.com/en/articles/1717274-adding-comment-count-links-to-your-home-page). It's just that using it on an AMP page requires some modifications to the HTML.

**Comment by maciejmackowiak** [comment]
Hi @Hovspian 
Can you help me out?

As per AMP documentation remote scripts can be loaded via `<amp-script>` and if they are cross-origin then "script hash" must be added to `<head>`
https://amp.dev/documentation/components/amp-script/?format=websites#load-javascript-from-a-remote-url
`<script>` can be used only for local scripts
https://amp.dev/documentation/components/amp-script/?format=websites#load-javascript-from-a-local-element

Using `<script>` instead of `<amp-script>`, adding the "content hash" is also not an option because:
> `amp-script` runs your custom JavaScript in a Web Worker that contains a virtual DOM. 
https://amp.dev/documentation/components/amp-script/?format=websites#how-does-it-work?

So using example from Disqus documentation will break AMP validation or am I missing something?
Maybe you have working AMP example that you can share?

Thanks
Maciej

**Comment by Hovspian** [comment]
Hi @maciejmackowiak,

Thanks for pointing that out. I went back to the documentation and it looks like I missed a couple of things. While the solution that I posted works, addressing the issues you brought up would be a good improvement because the instructions are currently breaking AMP guidelines.

I'll take another look and post an update with the changes.

**Comment by MrCsabaToth** [comment]
AMP Validation of `<script id="dsq-count-scr" src="//EXAMPLE.disqus.com/count.js" target="amp-script" async></script>` (Step 2) fails with:

1. The attribute 'async' may not appear in tag 'amp-script extension local script'.
2. The attribute 'src' may not appear in tag 'amp-script extension local script'.

at https://search.google.com/test/amp
![Screenshot_2020-04-30_01-16-04](https://user-images.githubusercontent.com/744949/80688158-3ce04880-8a80-11ea-8ceb-d7ca40baa48d.png)

**Comment by Hovspian** [comment]
Hi,

Sorry that it took so long to update, but I put up a new PR (#41) that updates the installation instructions to use an `<amp-list>` like @maciejmackowiak originally suggested. The new instructions use a new endpoint created for AMP comment counts that complies with the `<amp-list>` requirements.

**Comment by MrCsabaToth** [comment]
@Hovspian This looks promising, not requiring custom JS. I left a comment in the PR about `OTHER_URL` and `FOURTH_THREAD_IDENTIFIER`.

**Comment by Hovspian** [comment]
I'm closing this issue now that #41 is merged. Anyone should be able to add comment counts to AMP pages with the updated instructions.

**Comment by archon810** [comment]
Thanks for the fix. We've moved to this new solution on androidpolice.com. For example: https://www.androidpolice.com/2020/05/12/google-is-testing-imessage-like-reactions-for-rcs-chats-in-its-messages-app/?amp.
